name: Build & Publish

on:
  push:    
    branches:
      - "**"  # Build on all branches
    tags:
      - "v*"  # Publish only on tags

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write  # Required for GHCR
      contents: read

    env:
      TAG_NAME: ${{ github.ref_name }} # e.g. "v1.0.0"

    steps:
      - uses: actions/checkout@v4

      - name: Extract tag name without "v"
        id: prep
        run: echo "tag=${TAG_NAME#v}" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
          tags: ghcr.io/${{ github.repository }}:${{ steps.prep.outputs.tag }}
